---
title: "課?<a0>?練習模<e7><89><88>"
author: "kkqq123123123"
date: "2020-10-28"
output: output_format
params:
  id: "410886026"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
#連鎖選取(by vector)

numVector <- c(2, 3, 6, -1, 4, 2, 6)
select1 <- numVector[c(1, 4)]
select1
select2 <- select1[[1]]
select2

# 相當於
numVector[c(1, 4)][[1]]
```

```{r}
#連鎖選取(by logic)

select1 <- numVector[c(T, T, F, T, F, F, T)]
select1
select2 <- select1[c(1, 4)]
select2

# 相當於
numVector[c(T, T, F, T, F, F, T)][c(1, 4)]
```

```{r}
#連鎖選取應用

majorsStudent <- c("經濟學系", "經濟學系", "社會學系", "社工系", "經濟學系")
namesStudent <- c("小英", "小美", "大雄", "阿華", "阿尼")
genderStudent <- c("F", "F", "M", "F", "M")

majorsStudent

pickEcon = c(T,T,F,F,T)
namesStudent[pickEcon]
genderStudent[pickEcon]
```

```{r}
pickEconNum = c(1,2,5)
namesStudent[pickEconNum]
genderStudent[pickEconNum]
```

```{r}
#取出為經濟學系且為男性的學生

pickEconNum = c(1,2,5)
namesStudent[pickEconNum][[3]]
genderStudent[pickEconNum][[3]]
```

```{r}
today <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))
tomorrow <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))

weather <- list(today, tomorrow)

print(weather)
```

```{r}
#解析資料  利用str

str(weather,1)
str(weather,2)
str(weather,3)
```

```{r}
weather[[1]][[2]][[2]]  # 今天/新北市/highest_temp
weather[[2]][[2]][[2]]  # 明天/新北市/highest_temp
```




