---
title: "課?<a0>?練習模<e7><89><88>"
author: "kkqq123123123"
date: "2020-11-29"
output: output_format
params:
  id: "410886026"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
#Relational Operators

example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
#1.比較

#取出身高>=170的人
pick_above170 = example$height >= 170
example$name[pick_above170]
```

```{r}
#2.相等

#取出血型為B型的人
pick_bloodB = example$bloodType == "B"
example$name[pick_bloodB]
```

```{r}
#取出身高>=170且血型為B型的人(利用 "&" AND來完成)
example$name[pick_above170 & pick_bloodB]
```

```{r}
#可排序資料比較

#將factor的元素排序
example$allowance =
  factor(
    example$allowance,
    levels=c("0-1000", "1001-2000", "2000+"),
    ordered = T # 設定為可排序factor
  )

```

```{r}
#注意!  資料包含NA時 不可用==NA來判斷!!!!!!  需要用is.na(......)來判斷
a = c(22,NA,18) 
a==NA
is.na(a)
```




