---
title: "課?<a0>?練習模<e7><89><88>"
author: "kkqq123123123"
date: "2020-12-06"
output: output_format
params:
  id: "410886026"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
#字元字串

library(stringr)
library(glue)
```

```{r}
#先下載歌詞
thatsAlright <- 
  jsonlite::fromJSON(
    "https://www.dropbox.com/s/f3ox7rd5favr0o0/thatsAlright.json?dl=1"
  )

View(thatsAlright)
```

```{r}
# 字串向量長度
length(c("I will"))
# 每個元素值有幾個字元(包含符號與空格)
str_length(c("I will"))
```

```{r}
# 字串向量長度
length(thatsAlright)
# 每個元素值有幾個字元
str_length(thatsAlright)
```

```{r}
#切割字串
line67 <- thatsAlright[c(6,7)]

line67

str_split(line67, ", ")  #遇到, 時會分開句子
```

```{r}
#規律探測
pattern = "you" 
```

```{r}
#str_detect 回傳值為T/F向量

# 'you'是否出現在第1,2,3,...最後一句
pick_you = str_detect(thatsAlright, pattern="you")
str_view_all(thatsAlright[pick_you],"you")
```

```{r}
#str_which 回傳值為符合規律的元素位置

# 哪幾句有'you'出現
whichHas_you <- str_which(thatsAlright, pattern="you")
whichHas_you
str_view_all(thatsAlright[whichHas_you],"you")
```

```{r}
#str_subset

# 只留下有出現'you'字眼的句子
onlyYou <- str_subset(thatsAlright, pattern="you")

length(thatsAlright)
length(onlyYou)
```

```{r}
str_count

# 每一句有幾個"you"
countEach_you <- str_count(thatsAlright,
                           pattern="you")
countEach_you
str_view_all(
  thatsAlright[1:10], pattern="you")
```

```{r}
#正規表示式

Rmdfiles <- c("file1.Rmd", "file2.R", "file3.rmd", "file4.RMD", "myRmd.R")

SchoolIds <- c("410973029", "410988011", "410974023","410783025","710773022","410788021","410673124","410873051","49988001")

```

```{r}
#找出不分大小寫的Rmd?
#利用正規表示式  以[]來放入捲帶可能內容值
#正規表示式記得加上""(其為字串)
library(stringr)

regexPattern="(R|r)(M|m)(D|d)"

str_subset(
  Rmdfiles, pattern="(R|r)(M|m)(D|d)")

```

```{r}
#找出學號第一位為4  接著為108或109  再來是73或88?

regexPattern="[4](108|109)(73|88)"

str_subset(
  SchoolIds, 
  pattern = "[4](108|109)(73|88)")
```

```{r}
#如果卷帶裡只有一個值，可以不寫[], ()。

str_subset(
  SchoolIds,
  pattern="(4)(108|109)(73|88)")

str_subset(
  SchoolIds,
  pattern="4(108|109)(73|88)")
```











